version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: nc_backend_container
    ports:
      - "5000:5000"
    networks:
      - nc-network
    env_file:
      - ./backend/.env
  
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: nc_frontend_container
    ports:
      - "5173:5173"
    networks:
      - nc-network
    depends_on:
      - backend
  
networks:
  nc-network:
    driver: bridge


